on:
  schedule:
    - cron: '0 */5 * * *' # Cron A: Every 5 hours
    - cron: '0 0 * * *'   # Cron B: Daily at midnight UTC
  workflow_dispatch:

jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
      # ... (Checkout, Python Setup, Install Dependencies - These always run) ...

      - name: Cache sent_links.db # This step ALWAYS runs
        uses: actions/cache@v4
        with:
          path: sent_links.db
          key: ${{ runner.os }}-sent-links-db-v1
          restore-keys: |
            ${{ runner.os }}-sent-links-db-v1
        continue-on-error: true # Always try to restore cache, even if it fails

      - name: Run Bot Script # This step ALWAYS runs
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |
          export PYTHONPATH=$GITHUB_WORKSPACE/src:$PYTHONPATH
          python src/main.py
          # At the end of this job, actions/cache automatically SAVES the cache if it changed.

      - name: Upload sent_links.db as long-term backup # This step runs ONLY if its 'if' condition is true
        uses: actions/upload-artifact@v4
        # <--- اینجا نکته کلیدی است:
        if: github.event_name == 'schedule' && github.event.schedule == '0 0 * * *'
        with:
          name: sent_links.db-backup
          path: sent_links.db
          overwrite: true
          retention-days: 10000
