name: AI News Aggregator Bot

on:
  schedule:
    - cron: '0 */5 * * *' # Runs every 5 hours
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Cache sent_links.db # <--- NEW STEP: Using actions/cache for persistence
      uses: actions/cache@v4 # Using actions/cache@v4 (latest stable major version)
      with:
        path: sent_links.db # Path to your database file in the repo root
        key: ${{ runner.os }}-sent-links-db-v1 # Unique key for this cache, includes OS and a version
        restore-keys: | # Defines fallback keys for restoring stale cache
          ${{ runner.os }}-sent-links-db-v1
          
    - name: Run Bot Script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        GITHUB_WORKSPACE: ${{ github.workspace }} # Pass GITHUB_WORKSPACE to your script
      run: |
        export PYTHONPATH=$GITHUB_WORKSPACE/src:$PYTHONPATH
        python src/main.py
        
    # IMPORTANT: No actions/upload-artifact step is needed here.
    # actions/cache automatically saves the cache at the end of the job
    # if the content of 'path' has changed.
