name: AI News Aggregator Bot

on:
  schedule:
    # Runs every 5 hours
    - cron: '0 */5 * * *' # Changed to every 5 hours as per your last update
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Download sent_links.db (if exists from previous run)
      uses: actions/download-artifact@v4
      with:
        name: sent-links-db
        path: . # Download to the root of the repository
        
    - name: Run Bot Script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
      run: |
        export PYTHONPATH=$GITHUB_WORKSPACE/src:$PYTHONPATH
        python src/main.py
        
    - name: Upload sent_links.db
      uses: actions/upload-artifact@v4
      with:
        name: sent-links-db # Name of the artifact
        path: sent_links.db # Path to the database file
        if-no-files-found: ignore # Don't fail if the file wasn't created (e.g., first run)
        retention-days: 100000 # Keep the artifact for 7 days (optional, can be adjusted)
