name: AI News Aggregator Bot

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Download sent_links.db (if exists from previous run)
      uses: actions/download-artifact@v4
      with:
        name: sent-links-db
        path: . # Download to the root of the repository
        # This step will fail on first run if artifact doesn't exist,
        # but that's expected. It won't stop subsequent steps due to `continue-on-error`.
        # Alternatively, you can use `continue-on-error: true` here but it's not best practice.
        # It's okay for it to fail as long as `upload` works.
    continue-on-error: true # <--- ADD THIS LINE: Allows the workflow to proceed even if download fails (e.g., on first run)
    
    - name: Run Bot Script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        # Pass GITHUB_WORKSPACE to your script as an environment variable
        # so db.py can construct the absolute path correctly.
        GITHUB_WORKSPACE: ${{ github.workspace }}
      run: |
        export PYTHONPATH=$GITHUB_WORKSPACE/src:$PYTHONPATH
        python src/main.py
        
    - name: Upload sent_links.db
      uses: actions/upload-artifact@v4
      with:
        name: sent-links-db
        path: sent_links.db # Path to the database file (at repo root)
        # if-no-files-found: ignore # <--- REMOVE THIS LINE
        retention-days: 100000
